# stages:
#   - build
#   - test
#   - deploy

# build:
#   stage: build
#   services:
#     - mongo:latest
#   script:
#     - cd pet
#     - npm install
#     - cd ../backend
#     - go mod download
#     - go build -o main .

# test:
#   stage: test
#   script:
#     - cd backend
#     - go test ./...

# deploy:
#   stage: deploy
#   script:
#     - echo "Deploying application..."
